name: "nightly schema generator"
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  nightly:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo first
      uses: actions/checkout@v4.2.2
    - name: Then clone the workers-sdk repo
      uses: actions/checkout@v4.2.2
      id: metadata
      with:
        repository: cloudflare/workers-sdk
        path: workers-sdk
        ref: main
    - name: Setup Node.js environment (uses latest LTS release)
      uses: actions/setup-node@v3.9.1
      with:
        node-version: 22
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: 9.12.0
    - name: Generate schema
      run: |
        cd ${{github.workspace}}/workers-sdk && pnpm install
        cd ${{github.workspace}}/workers-sdk/packages/wrangler
        pnpm run generate-json-schema
        cp ${{github.workspace}}/workers-sdk/packages/wrangler/config-schema.json ${{github.workspace}}/config-schema.json
    - name: Commit and push
      run: |
        git stage config-schema.json
        git commit --signoff -m "generate workers config schema from workers-sdk repo" -m "Commit-Id: https://github.com/cloudflare/workers-sdk/commit/${{steps.metadata.outputs.commit}}" -m "Co-authored-by: Andrei Jiroh Halili <ajhalili2006@crew.recaptime.dev>
        git push
      env:
        GIT_AUTHOR_NAME: Recap Time Bot
        GIT_AUTHOR_EMAIL: "recaptimebot@gmail.com" #TODO: Use git@recaptime.dev soon
